"""Physics, power unit, sensor and fitness constants for Formula NEAT.

`car.py` reads everything through `self.cfg`, in pixel units: speeds in pixels
per tick, accelerations in pixels per tick squared, distances in pixels.

The catch is that every track has its own metre scale. Tracks are generated by
`tools/build_tracks.py`, which sizes the car from each track's own band width so
a track is always about six cars wide - the real proportion - and then anchors
the scale so the car is exactly a real 5.63m Formula 1 car. A pixel is therefore
worth 0.09m on the oval and 0.24m on Shanghai.

So the physics is defined here in REAL units - km/h, m/s^2, newtons, metres -
and `cfg_for_track()` converts it into the pixel units car.py wants using that
track's own scale. The same car then behaves the same way on every circuit.

Cornering
---------
`car.py` estimates a turn radius from the steering angle with a bicycle model
and crashes the car when the centrifugal force on a 768kg car exceeds the grip
available. The practical effect is a speed/steering envelope: the faster you go,
the less you may turn. `tools/calibrate.py` prints that envelope per track.
"""

import copy

# --------------------------------------------------------------------------
# Real-world anchors. These are what you tune.
# --------------------------------------------------------------------------

REAL = {
    # --- car ------------------------------------------------------------
    "car_length_m": 5.63,
    "car_width_m": 2.00,
    "mass_kg": 768.0,          # matches car.py
    "wheelbase_m": 3.40,       # matches car.py

    # --- speed ----------------------------------------------------------
    "top_speed_kmh": 320.0,
    # X mode trades downforce for straight-line speed.
    "x_mode_bonus_kmh": 26.0,
    "override_bonus_kmh": 18.0,
    # A car is never fully stopped; below this it is retired for stalling.
    "min_speed_kmh": 35.0,

    # --- acceleration ---------------------------------------------------
    # About 1.4g of drive and 4.6g of braking, which is roughly a real car.
    "engine_accel_mps2": 14.0,
    "brake_decel_mps2": 45.0,
    "override_boost_mps2": 7.0,

    # --- grip -----------------------------------------------------------
    # Peak lateral grip on fresh tyres in Z mode: ~4.4g on a 768kg car.
    "grip_limit_n": 33000.0,
    "z_mode_grip_mult": 1.0,
    "x_mode_grip_mult": 0.72,

    # --- sensing --------------------------------------------------------
    "radar_range_m": 70.0,
    # How close another car must be for the manual override to unlock.
    "override_range_m": 22.0,
}


# --------------------------------------------------------------------------
# Scale-free constants. These mean the same thing on every track.
# --------------------------------------------------------------------------

SIM_CFG = {
    # --- rendering ------------------------------------------------------
    "screen_width": 1920,
    "screen_height": 1080,
    "fps": 60,
    "border_color": (255, 255, 255, 255),
    "car_sprite_path": "assets/cars/car.png",

    # --- fallback car size ----------------------------------------------
    # Used only for a track whose metadata carries no car block.
    "car_size_x": 62,
    "car_size_y": 22,
    "sensor_nose_offset": 31,
    "pixel_to_meter": 0.0908,

    # --- sensors --------------------------------------------------------
    "radar_max_distance": 260,
    # Fixed radar step, used only when a track carries no clearance field.
    # Anything above 1 can straddle a wall at a glancing angle and report the
    # far side of it, so the safe fallback is 1.
    "radar_coarse_step": 1,
    # Filled in by main.py from the track's clearance image.
    "clearance_field": None,
    "radar_angles": [-90, -45, 0, 45, 90],

    # --- tyres ----------------------------------------------------------
    "grip_base": 1.0,
    # Tuned so a car loses roughly half its grip over a long stint.
    "grip_wear_rate": 0.00015,

    # --- steering (degrees per tick, so already scale-free) --------------
    "steer_max_per_tick": 4.0,
    "steer_to_wheel_angle": 6.0,
    "max_wheel_angle_deg": 22.0,

    # --- battery, as a 0..1 fraction of a full store ---------------------
    # A full store is worth about five seconds of maximum deployment.
    "battery_deploy_rate": 0.0035,
    "battery_harvest_brake": 0.0060,
    "battery_harvest_lift": 0.0012,
    "battery_override_drain": 0.0100,

    # --- manual override ------------------------------------------------
    # Deliberately 0. car.py stamps `last_override_tick` on every tick the
    # override is active, so any non-zero cooldown makes the override fire for a
    # single tick and then lock itself out. Battery drain is the real limiter.
    "override_cooldown_ticks": 0,

    # --- fitness --------------------------------------------------------
    # Progress has to out-earn presence. With the original weights a car that
    # simply sat on the racing line at minimum speed banked 2.08 per tick -
    # 2495 over a generation - while a whole lap of the oval paid 580. The
    # optimum was to crawl, and that is exactly what training converged on.
    "reward_checkpoint": 18.0,
    "reward_lap": 220.0,
    "reward_apex": 2.2,
    # Racing-line reward: full value on the line, zero `falloff` px away from
    # it, negative beyond. cfg_for_track sets the falloff from track width.
    "reward_line_max": 0.30,
    "reward_line_falloff": 55.0,
    # Pace pays up to this much per tick at top speed; cfg_for_track divides it
    # by top speed in px/tick, since car.py multiplies it back by raw speed.
    "reward_pace": 1.0,
    "reward_battery_ok": 0.05,
    "penalty_battery_low": 0.35,
    # Must exceed reward_line_max + reward_battery_ok, or a car sitting on the
    # line at minimum speed still banks a positive score for doing nothing.
    "penalty_time": 0.50,
    "penalty_steering": 0.01,

    # --- derived from REAL by cfg_for_track ------------------------------
    "max_speed_base": 16.3,
    "min_speed": 1.8,
    "x_mode_speed_bonus": 1.3,
    "override_speed_bonus": 0.9,
    "engine_accel": 0.0714,
    "brake_decel": 0.2295,
    "override_boost": 0.0357,
    "drag_coeff": 0.000258,
    "base_grip_limit_n": 33000.0,
    "z_mode_grip_mult": 1.0,
    "x_mode_grip_mult": 0.72,
    "override_distance_px": 242,
}


def make_cfg(**overrides):
    """A copy of the defaults with individual constants replaced."""
    cfg = copy.deepcopy(SIM_CFG)
    unknown = set(overrides) - set(cfg)
    if unknown:
        raise KeyError(f"unknown sim config keys: {sorted(unknown)}")
    cfg.update(overrides)
    return cfg


def cfg_for_track(track_meta, real=None, **overrides):
    """Config for one track: real-world physics converted to its pixel scale.

    `track_meta` is a track's JSON. Its `car` block gives the car's pixel size
    and the metres-per-pixel that makes that car a real Formula 1 car; every
    speed, acceleration and distance below is converted through it, so the car
    drives identically on a circuit drawn at 0.09 m/px and one at 0.24 m/px.
    """
    cfg = copy.deepcopy(SIM_CFG)
    values = dict(REAL)
    if real:
        unknown = set(real) - set(values)
        if unknown:
            raise KeyError(f"unknown real-world keys: {sorted(unknown)}")
        values.update(real)

    car = track_meta.get("car")
    if car:
        cfg["car_size_x"] = car["size_x"]
        cfg["car_size_y"] = car["size_y"]
        cfg["sensor_nose_offset"] = max(1, car["size_x"] // 2)
        cfg["pixel_to_meter"] = car["pixel_to_meter"]

    metres_per_pixel = cfg["pixel_to_meter"]
    fps = cfg["fps"]

    def speed(kmh):
        """km/h -> pixels per tick."""
        return (kmh / 3.6) / (metres_per_pixel * fps)

    def accel(mps2):
        """m/s^2 -> pixels per tick squared."""
        return mps2 / (metres_per_pixel * fps * fps)

    def length(metres):
        return metres / metres_per_pixel

    cfg["max_speed_base"] = speed(values["top_speed_kmh"])
    cfg["min_speed"] = speed(values["min_speed_kmh"])
    cfg["x_mode_speed_bonus"] = speed(values["x_mode_bonus_kmh"])
    cfg["override_speed_bonus"] = speed(values["override_bonus_kmh"])

    cfg["engine_accel"] = accel(values["engine_accel_mps2"])
    cfg["brake_decel"] = accel(values["brake_decel_mps2"])
    cfg["override_boost"] = accel(values["override_boost_mps2"])
    # Drag balances full power a shade above the HIGHEST attainable speed, so
    # the car accelerates asymptotically towards each mode's cap rather than
    # slamming into it - and, importantly, so every cap is actually reachable.
    # Balancing at the base cap instead leaves X mode drag-limited below its
    # own limit, which makes X pure downside: it pays 28% grip for a few km/h.
    terminal = (
        cfg["max_speed_base"]
        + cfg["x_mode_speed_bonus"]
        + cfg["override_speed_bonus"]
    ) * 1.02
    cfg["drag_coeff"] = cfg["engine_accel"] / (terminal * terminal)

    # Force is already physical, so it needs no conversion at all - which is
    # the whole point of stating the grip limit in newtons.
    cfg["base_grip_limit_n"] = values["grip_limit_n"]
    cfg["z_mode_grip_mult"] = values["z_mode_grip_mult"]
    cfg["x_mode_grip_mult"] = values["x_mode_grip_mult"]

    cfg["radar_max_distance"] = int(round(length(values["radar_range_m"])))
    cfg["override_distance_px"] = int(round(length(values["override_range_m"])))

    # car.py multiplies reward_pace by raw px/tick speed, so divide through by
    # top speed here and the term pays the same on every track.
    cfg["reward_pace"] = cfg["reward_pace"] / cfg["max_speed_base"]
    # Staying on the line should mean the same relative to track width.
    width = track_meta.get("median_width_px")
    if width:
        cfg["reward_line_falloff"] = max(20.0, width * 0.42)

    if overrides:
        unknown = set(overrides) - set(cfg)
        if unknown:
            raise KeyError(f"unknown sim config keys: {sorted(unknown)}")
        cfg.update(overrides)
    return cfg
