"""Track loading: image, collision mask and the metadata `car.py` drives against.

Track metadata is generated by `tools/build_tracks.py` from the track image, so
the checkpoints and racing line are guaranteed to sit on the track rather than
being placed by hand.
"""

import json
import math
import os

import pygame

ROOT = os.path.dirname(os.path.abspath(__file__))
TRACK_DIR = os.path.join(ROOT, "assets", "tracks")


def available():
    return sorted(
        os.path.splitext(name)[0]
        for name in os.listdir(TRACK_DIR)
        if name.endswith(".json")
    )


class Track:
    """A drivable circuit plus everything the car and the fitness need from it."""

    def __init__(self, name):
        path = os.path.join(TRACK_DIR, f"{name}.json")
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"no track named {name!r}; available: {', '.join(available())}"
            )
        with open(path) as handle:
            self.meta = json.load(handle)

        self.name = self.meta["name"]
        self.spawn = self.meta["spawn"]
        self.racing_line = [tuple(p) for p in self.meta["racing_line"]]
        self.length_px = self.meta["length_px"]
        self.width_px = self.meta["median_width_px"]
        self.surface = None
        self.border_mask = None
        self.clearance = None

    @property
    def resolution(self):
        return tuple(self.meta["resolution"])

    def load(self, border_color):
        """Build the render surface and the collision mask. Needs a display."""
        image = os.path.join(ROOT, self.meta["image"])
        self.surface = pygame.image.load(image).convert()
        # A wall is any pixel at or above 200 on every channel, which is the
        # same definition tools/build_tracks.py uses for "off track" and the
        # same one baked into the clearance field. Keeping collision, radar and
        # clearance on one definition means a car cannot die a few pixels before
        # its sensors say the wall is there.
        self.border_mask = pygame.mask.from_threshold(
            self.surface, border_color[:3], (55, 55, 55, 255)
        )

        # Distance-to-wall map, used by the radars to ray-march instead of
        # testing every pixel. Optional: a track without one still works.
        clearance = self.meta.get("clearance_image")
        if clearance:
            path = os.path.join(ROOT, clearance)
            if os.path.exists(path):
                self.clearance = pygame.image.load(path).convert()
        return self

    def quietest_corner(self, width_frac=0.30, height_frac=0.46, step=4):
        """Which corner of the frame has the least track under it.

        The telemetry panel has to go somewhere, and a fixed corner hides cars
        on any circuit that happens to run through it - on Silverstone the whole
        pack disappeared behind it for seconds at a time. Sampling the track
        image picks the emptiest corner per track instead.

        Returns (x_fraction, y_fraction) for where the panel should sit.
        """
        if self.surface is None:
            return (0.0, 0.0)
        width, height = self.resolution
        panel_w = int(width * width_frac)
        panel_h = int(height * height_frac)

        # The four corners, plus the middle: a ring-shaped circuit has a large
        # empty infield, which is usually the best place of all for the panel.
        corners = {
            (0.0, 0.0): (0, 0),
            (1.0, 0.0): (width - panel_w, 0),
            (0.0, 1.0): (0, height - panel_h),
            (1.0, 1.0): (width - panel_w, height - panel_h),
            (0.5, 0.5): ((width - panel_w) // 2, (height - panel_h) // 2),
        }
        best_key, best_count = (0.0, 0.0), None
        for key, (x0, y0) in corners.items():
            count = 0
            for y in range(y0, y0 + panel_h, step):
                for x in range(x0, x0 + panel_w, step):
                    pixel = self.surface.get_at((x, y))
                    if pixel[0] < 200 or pixel[1] < 200 or pixel[2] < 200:
                        count += 1
            if best_count is None or count < best_count:
                best_key, best_count = key, count
        return best_key

    def car_meta(self):
        """The subset `car.py` reads out of a track."""
        return {
            "checkpoints": self.meta["checkpoints"],
            "racing_line": self.racing_line,
            "apex_indices": self.meta["apex_indices"],
        }

    def _line_index_behind(self, steps):
        return (-steps) % len(self.racing_line)

    def heading_at(self, index):
        """Direction of travel at a racing-line point, in car.py's angle space."""
        line = self.racing_line
        ahead = line[(index + 1) % len(line)]
        behind = line[index - 1]
        return -math.degrees(
            math.atan2(ahead[1] - behind[1], ahead[0] - behind[0])
        ) % 360

    def grid_slots(self, count, cfg, columns=3):
        """Starting positions for a field of cars, as a staggered F1-style grid.

        Cars line up in rows back from the start line, offset side to side within
        the track width. Spacing them out matters: it gives the manual override
        someone to actually chase, and stops the whole field from sharing one
        set of sensor readings on lap one.
        """
        line = self.racing_line
        spacing = max(1, int(round(self.length_px / len(line))))
        row_gap = max(1, int(round(cfg["car_size_x"] * 1.8 / spacing)))
        lateral = self.width_px * 0.26

        slots = []
        for i in range(count):
            row, column = divmod(i, columns)
            index = self._line_index_behind(row * row_gap)
            point = line[index]
            angle = self.heading_at(index)

            # Offset across the track, perpendicular to the direction of travel.
            heading = math.radians(360 - angle)
            across = (-math.sin(heading), math.cos(heading))
            side = (column - (columns - 1) / 2.0) / max(1.0, (columns - 1) / 2.0)
            centre_x = point[0] + across[0] * side * lateral
            centre_y = point[1] + across[1] * side * lateral

            slots.append(
                {
                    "x": centre_x - cfg["car_size_x"] / 2.0,
                    "y": centre_y - cfg["car_size_y"] / 2.0,
                    "angle": angle,
                    # How far back down the road this slot starts. The back of a
                    # 40-car grid is hundreds of pixels behind the line, and it
                    # has to drive all of that before checkpoint 0 counts.
                    "behind_px": row * row_gap * spacing,
                }
            )
        return slots
