"""Track loading: image, collision mask and the metadata `car.py` drives against.

Track metadata is generated by `tools/build_tracks.py` from the track image, so
the checkpoints and racing line are guaranteed to sit on the track rather than
being placed by hand.
"""

import json
import math
import os

import pygame

ROOT = os.path.dirname(os.path.abspath(__file__))
TRACK_DIR = os.path.join(ROOT, "assets", "tracks")


def available():
    return sorted(
        os.path.splitext(name)[0]
        for name in os.listdir(TRACK_DIR)
        if name.endswith(".json")
    )


class Track:
    """A drivable circuit plus everything the car and the fitness need from it."""

    def __init__(self, name):
        path = os.path.join(TRACK_DIR, f"{name}.json")
        if not os.path.exists(path):
            raise FileNotFoundError(
                f"no track named {name!r}; available: {', '.join(available())}"
            )
        with open(path) as handle:
            self.meta = json.load(handle)

        self.name = self.meta["name"]
        self.spawn = self.meta["spawn"]
        self.racing_line = [tuple(p) for p in self.meta["racing_line"]]
        self.length_px = self.meta["length_px"]
        self.width_px = self.meta["median_width_px"]
        self.surface = None
        self.border_mask = None

    @property
    def resolution(self):
        return tuple(self.meta["resolution"])

    def load(self, border_color):
        """Build the render surface and the collision mask. Needs a display."""
        image = os.path.join(ROOT, self.meta["image"])
        self.surface = pygame.image.load(image).convert()
        # Everything close to the border colour is a wall, which covers the
        # anti-aliased pixels along the edge of the painted track.
        self.border_mask = pygame.mask.from_threshold(
            self.surface, border_color[:3], (40, 40, 40, 255)
        )
        return self

    def car_meta(self):
        """The subset `car.py` reads out of a track."""
        return {
            "checkpoints": self.meta["checkpoints"],
            "racing_line": self.racing_line,
            "apex_indices": self.meta["apex_indices"],
        }

    def _line_index_behind(self, steps):
        return (-steps) % len(self.racing_line)

    def heading_at(self, index):
        """Direction of travel at a racing-line point, in car.py's angle space."""
        line = self.racing_line
        ahead = line[(index + 1) % len(line)]
        behind = line[index - 1]
        return -math.degrees(
            math.atan2(ahead[1] - behind[1], ahead[0] - behind[0])
        ) % 360

    def grid_slots(self, count, cfg, columns=3):
        """Starting positions for a field of cars, as a staggered F1-style grid.

        Cars line up in rows back from the start line, offset side to side within
        the track width. Spacing them out matters: it gives the manual override
        someone to actually chase, and stops the whole field from sharing one
        set of sensor readings on lap one.
        """
        line = self.racing_line
        spacing = max(1, int(round(self.length_px / len(line))))
        row_gap = max(1, int(round(cfg["car_size_x"] * 1.8 / spacing)))
        lateral = self.width_px * 0.26

        slots = []
        for i in range(count):
            row, column = divmod(i, columns)
            index = self._line_index_behind(row * row_gap)
            point = line[index]
            angle = self.heading_at(index)

            # Offset across the track, perpendicular to the direction of travel.
            heading = math.radians(360 - angle)
            across = (-math.sin(heading), math.cos(heading))
            side = (column - (columns - 1) / 2.0) / max(1.0, (columns - 1) / 2.0)
            centre_x = point[0] + across[0] * side * lateral
            centre_y = point[1] + across[1] * side * lateral

            slots.append(
                (
                    centre_x - cfg["car_size_x"] / 2.0,
                    centre_y - cfg["car_size_y"] / 2.0,
                    angle,
                )
            )
        return slots
